mcp-getgather/mcp-getgather

.github/workflows/deploy-getgather-dev-tailscale.yml
Deploy script and secrets added to deploy the the app to the VM with Tailscale on it. I'll monitor this closely to see if it's deployed properly, and I'll also be removing it from the other repo for the time being, so they don't overlap.
=> Deploy to Google Cloud VM with Tailscale

.github/workflows/deploy-dokku.yml
Added a tailscale step to our github actions deploy workflow so that we don't have to use the public IP for the VM. Once this works we can set a firewall to block incoming traffic on SSH port 22 (the default port for dokku I think).
=> Tailscale on Github Actions

Dockerfile
As suggested in the documentation:
https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
This is also better, since it doesn't rely on downloading and executing the install script every single time.
=> Container: alternative faster way to install uv

Dockerfile, entrypoint.sh
Joe's Window Manager, used in many small Linux distributions like Puppy or DSL, is notoriously lightweight (3 MB idle). Prefer that instead of XFCE4 (reported to consume 70 MB just when idle).
https://joewing.net/projects/jwm/
=> Container: favor jwm instead of the heavier XFCE4

Dockerfile, README.md, entrypoint.sh
To verify, build and run the container image using Podman or Docker:
```bash
podman build -t getgather .
podman run -p 8000:8000 --rm -e VNC_PASSWORD=secret -p 6080:6080 getgather
```
(Note the lack of mapping for port 5900 for VNC).
Then simply open `localhost:6080` with a web browser.
=> Container: use noVNC web-based VNC client for remove view

Dockerfile, README.md, entrypoint.sh, getgather/api/frontend/live.html, getgather/api/main.py, pyproject.toml, uv.lock
Because this web-based VNC needs to run at localhost:8000/live and not at localhost:6080, we can't use the standard built of novnc and websockify anymore.
To verify, first run a VNC server session. The easiest is to use GetGather container itself (note that only port 5900 is mapped, for VNC):
```
docker build -t getgather .
docker run -p 5900:5900 getgather
```
Then run this MCP server locally:
```
uv run -m uvicorn getgather.api.main:app
```
While `localhost:8000` should serve the main GetGather page, now `localhost:8000/live` should display the Linux desktop via VNC.
=> Use noVNC to serve live (desktop) view at /live

getgather/connectors/brand_specs/officedepot/specs.yml
Make certain "click" fields "autoclick" because we don't need user into to know to click them.
=> Autoclick in Office Depot

getgather/mcp/brand/alltrails.py, getgather/mcp/brand/amain.py, getgather/mcp/brand/amazon.py, getgather/mcp/brand/bbc.py, getgather/mcp/brand/cnn.py, getgather/mcp/brand/ebird.py, getgather/mcp/brand/shopee.py, getgather/mcp/brand/tokopedia.py
- remove unused mcp context, since we didn't use session_id from the context
- fix typo on ebird tool
=> refactor: remove unused mcp context

getgather/api/frontend/old-index.html, getgather/mcp/tools.md
Document the current tools available via MCP in a separate .md file on github. Added a link to the Getgather home page that redirects to said file.
=> MCP Documentation

getgather/connectors/brand_specs/kindle/specs.yml, getgather/flow.py, getgather/mcp/brand/kindle.py
Explicitly wait for `slurp_selector` so extraction is more reliable
TODO: need a different way to extract url since there is no `<a>` tag on the page
Verified Kindle auth and extraction with Claude Desktop
=> Add Kindle spec and mcp

package.json
Disable `concurrently` formatting so that uvicorn can print out to entire terminal width, otherwise it's limited to 80 characters
We will need to distinguish backend and front logs by the format, which isn't too bad
=> Make uvicorn logging use all terminal width

getgather/auth_orchestrator.py, getgather/config.py
We may eventually want to block images etc at the proxy service level but first stab it doesn't seem to be as simple as I thought. 
This is a nice ratchet and we can eventually followup with that.
=> add toggle for blocking unwanted resources (e.g. images)

frontend/index.html, frontend/src/components/Layout.tsx, frontend/src/pages/GetStarted.tsx, frontend/src/pages/Settings.tsx
updating the name of the getgather portal to be "GetGather Station" instead of "GetGather Studio", simply because studio is used at different places already and internally confusing.
=> rename GetGather Portal to GetGather Station

Dockerfile, test
- Debian 13 "Trixie" was released Aug 9, 2025. Python 3.13-slim images started using Trixie by default, but Playwright doesn't support it yet and tries to install deprecated font packages.
=> fix: Dockerfile, pinning docker base image to bookworm

getgather/api/main.py, getgather/mcp/brand/alltrails.py, getgather/mcp/brand/amain.py, getgather/mcp/brand/amazon.py, getgather/mcp/brand/astro.py, getgather/mcp/brand/audible.py, getgather/mcp/brand/bbc.py, getgather/mcp/brand/cnn.py, getgather/mcp/brand/doordash.py, getgather/mcp/brand/ebird.py, getgather/mcp/brand/gofood.py, getgather/mcp/brand/goodreads.py, getgather/mcp/brand/hardcover.py, getgather/mcp/brand/kindle.py, getgather/mcp/brand/shopee.py, getgather/mcp/brand/tokopedia.py, getgather/mcp/brand/ubereats.py, getgather/mcp/brand/zillow.py, getgather/mcp/calendar_utils.py, getgather/mcp/main.py, getgather/mcp/registry.py
Create 3 types of bundles
- "all" bundle has all brands and tools
- [brand] bundle has tools from a single brand
- [category] bundle has tools from a category of brands, e.g., books, food
Added `brand_id` to the `BrandMCPBase` class for convenience
Now the mcp client can use the config like the following to pick different bundles
```
{
"mcpServers": {
"getgather": {
"command": "npx",
"args": ["mcp-remote", "http://127.0.0.1:8000/mcp", "--allow-http"]
},
"getgather-books": {
"command": "npx",
"args": ["mcp-remote", "http://127.0.0.1:8000/mcp-books", "--allow-http"]
},
"getgather-amazon": {
"command": "npx",
"args": ["mcp-remote", "http://127.0.0.1:8000/mcp-amazon", "--allow-http"]
}
}
}
``` 
Here are the screenshots of the above configuration
=> Create separate mcp servers for different bundles of brands and tools

getgather/mcp/brand/amazon.py, getgather/parse.py
Background 
The parse function took too long when we give the html directly, because it tries to create a new headless instance based on the html given. When using the parse, we already have the page and can use that to find what we need. 
This PR is part of #129. We're solving too many problems with undecided solution in that PR, so I'm creating a new PR to tackle each one to make it clearer. 
Can search product with no problem:
=> fix: search product on amazon

getgather/connectors/spec_models.py, getgather/mcp/brand/amazon.py, getgather/parse.py
The amazon search product tools can be very slow. Tried searching for tumbler, it gives ~60 products, but I need to wait for more than a minute to get result. 
In cases like this where we're getting in bulk, I think we can use evaluate to make the process faster, because we don't have to do back and forth between browser and python. 
Using `evaluate` we can save more time significantly when there are a lot of search result. For this instance, we can reduce HTML parsing time from 105.2 s to 0.2s. 
This is what happen with locator:
```
[PARSE] Using locator extraction method
[PARSE] Starting locator-based data extraction from page...
[PARSE] Found 60 rows in 0.216s using locators
[PARSE] Row 1 processed in 1.902s
[PARSE] Row 2 processed in 1.615s
[PARSE] Row 3 processed in 1.693s
[PARSE] …
```
=> fix: slow search product amazon

entrypoint.sh, getgather/api/main.py
so the browser can use the same port 9999 to access inspector `http://localhost:9999/inspector/?MCP_PROXY_AUTH_TOKEN=getgather`
=> add a /inspector proxy endpoint

getgather.py, getgather/connectors/brand_specs/goodreads/goodreads-books.html, getgather/connectors/brand_specs/goodreads/goodreads-overlay.html, getgather/connectors/brand_specs/goodreads/goodreads-select-signin.html, getgather/connectors/brand_specs/goodreads/goodreads-signin.html, getgather/connectors/brand_specs/goodreads/goodreads-signup.html, getgather/connectors/brand_specs/goodreads/goodreads-siteheader.html, getgather/distill.py, pyproject.toml, uv.lock
This is mainly copied from Middleman with very little modification. I plan to have a follow-up which will do the following:
* Use a proper and richer logging
* Avoid custom browser code and reuse the existing abstraction
* Switch to idiomatic Pydantic
For now, try this by running:
```bash
./getgather.py run goodreads.com/review
```
and you'll be prompted for email and password. If nothing goes wrong, the list of books will be printed out in its original HTML table.
And to run a simple distillation:
```bash
./getgather.py distill https://www.goodreads.com/user/sign_in
```
=> Manual distillation test via CLI

pyproject.toml, uv.lock
fastmcp added the fixes we need so we can go back to use their main
we can switch to pypi when they release next time
=> remove fastmcp fork

getgather/mcp/main.py, getgather/mcp/nytimes.py, getgather/mcp/patterns/nytimes-best-sellers.html
This is just the first step. The next step is to incorporate some parsing so that the raw-ish HTML can be turned into JSON.
To try, launch as usual with `npm run dev` and use MCP Inspector to invoke the tool named `nytimes_get_bestsellers_list`.
Alternatively, use Claude or other MCP client.
=> Distillation-based MCP tool to get NYTimes Bestsellers

getgather/mcp/auth.py
- using mcp-session-id for user identifier
=> feat: x-getgather-custom-app using mcp session as auth

getgather/browser/profile.py, getgather/browser/session.py, getgather/config.py, getgather/rrweb.py
It turns out Playwright has API to bypass CSP, so I used it's built-in parameter. CSP setting are no longer needed.
- The tests for BBC are still green after the code was removed
=> feat: bypass CSP

getgather/mcp/shared.py
- Fixed KeyError crash when polling auth status for non-existent/expired links
The poll_status_hosted_link function assumed all API responses would contain a status field, but HTTP 404 responses from FastAPI have a different structure ({"detail": "error message"}) without this field, causing KeyError: 'status'.
```
/25 06:33:13] ERROR    Error calling tool 'poll_auth'  tool_manager.py:233
2025-09-09T06:33:13.802657661Z app[web.1]:                              ╭─ Traceback (most recent cal─╮
2025-09-09T06:33:13.802664432Z app[web.1]:                              │ /opt/venv/lib/python3.13/si │
2025-09-09T06:33:13.802669608Z app[web.1]:                              │ te-packages/fastmcp/tools/t │
2025-09-09T06:33:13.802674498Z app[web.1]:                              │ ool_manager.py:224 in …
```
=> fix: hosted-link not found

.github/workflows/api-signin-tests.yml, .github/workflows/webui-tests.yml, tests/api/test_signin_api.py, tests/api/test_webui_signin.py, tests/connectors/brand_specs/acme-email-and-password-navigate-action.yml, tests/connectors/brand_specs/acme-email-and-password-then-mfa.yml
Update our previously termed "authentication" tests to "signin" tests to reflect the new verbiage that authentication is for the MCP server and signin is for individual brands.
=> Update tests with signin language

.github/workflows/distill-tests.yml, tests/distillation/patterns/acme_authentication_error.html, tests/distillation/patterns/acme_email_and_password.html, tests/distillation/patterns/acme_home_page.html, tests/distillation/patterns/acme_login_success.html, tests/distillation/patterns/acme_universal_error_test.html, tests/distillation/test_distill.py
Adds a new distillation test for the `run_distillation_loop` function with the ACME email and password page. This tests the actual ability of the distill framework to autofill email and password and click submit. The only thing needed is to add the email and password to the .env file with the proper names.
You can test it out by running `uv run pytest tests/distillation/test_distill.py -v -s` in the terminal. Be sure to first set 
```
ACME_EMAIL_AND_PASSWORD_EMAIL=joe@example.com
ACME_EMAIL_AND_PASSWORD_PASSWORD=trustno1
```
in your .env file first and run `source .env` to reset env vars before running the above command.
=> Distillation Test with Sign In

getgather.py, getgather/distill.py, getgather/mcp/dpage.py
This is necessary to avoid the potential infinite loop, e.g. in the case of repeated incorrect credentials. It is a port of the same mechanism in Middleman (https://github.com/mcp-getgather/middleman/pull/30).
The idea is that when an input field is filled, either on the CLI or from the distilled page, the value for that field also changes the distilled version of the page. This way, when that page is submitted (via form) to the upstream server and the server comes back with another sign-in form, it will not be considered the same thing (they are not).
To verify, run the usual CLI: `./getgather.py run goodreads.com/review`.
Before this change, the distillation loop never considers that the second incorrect passsword alert as a different once.
After this change, everything works as …
=> Adopt the input value when it is being filled

getgather/mcp/main.py
Fixed a validation error in the \`/api/docs-mcp\` endpoint by making the description field optional in the 
MCPToolDoc model. The endpoint was failing with a 500 error because some MCP tools had null descriptions, 
but the model required a string value.
- Updated \`mcp_app_docs\` function to provide fallback text: \`tool.description or \"No description 
provided\"\`
- Maintains strict typing while ensuring consistent user experience
This is a minimal fix that maintains backward compatibility while resolving the immediate crash. The 
endpoint will now successfully return documentation for all MCP tools, with missing descriptions showing as
null in the JSON response."
```sh
│    250 │   │   """ …
```
=> fix: provide default descriptions for MCP tools 

getgather/mcp/brand/amazon.py, getgather/mcp/brand/amazonca.py
Enhanced the Amazon MCP purchase history retrieval to use the distillation loop pattern with dynamic year filtering instead of the generic extract method. This provides more targeted data extraction for the current year's Amazon orders.
https://github.com/user-attachments/assets/a1845890-4500-4144-88c7-fe9dd0395f77
=> feat: replace extraction with distillation for amazon purchases

getgather/browser/profile.py
This should allow us to better understand when and why the X server is not found by playwright
=> check for display variable in code

getgather/mcp/auto_import.py, getgather/mcp/bbc.py, getgather/mcp/espn.py, getgather/mcp/main.py, getgather/mcp/nytimes.py, getgather/mcp/registry.py
This is mainly to assist gradual migration from orchestrator to distilation. Until every tool is completely migrated, expect some rough edges such as two category bundles, awkward/inconsistent typing, etc.
To verify, launch as usual with `npm run dev` and connect the MCP inspector to e.g. `localhost:23456/mcp-media`. A bunch of tools related to BBC, ESPN, and NYTimes should be available and accessible.
=> Base MCP for distillation-based tools

getgather/mcp/auto_import.py
Eventually when everything is migrated to distillation, we may not need this. But for now, avoid blind module import by checking first heuristically if the module is a legimate MCP class.
To verify, run the MCP server, connect MCP inspector, list some tools. All the available tools should be still enumerated correctly.
=> Fix autoimport by checking for the MCP class in the module source

.env.template, Dockerfile, entrypoint.sh, getgather/config.py, getgather/hosted_link_manager.py
rename SERVER_NAME to HOSTNAME to be consistent with gateway naming
make the fastapi port configurable so we can use 80 and gateway can reach the server just by hostname
=> minor changes in gateway mode

README.md
Built-in MCP Inspector was already removed in PR #386.
=> Remove docs on MCP Inspector

getgather/mcp/dpage.py, getgather/mcp/groundnews.py, getgather/mcp/main.py, getgather/mcp/patterns/groundnews-latest-stories.html
This also introduces the override for the timeout on the initial distillation, as Ground News usually displays an interstitial page for about 2-3 seconds.
To verify, run `npm run dev`, connect MCP Inspector, and launch the tool named `groundnews_get_stories`.
=> Ground News MCP tool, to get the latest stories

Dockerfile, entrypoint.sh
Before this PR, if one person is opening the `/live` desktop view, nobody else can connect to that, since by default the VNC server limits to a single connection.
After this PR, by enabling the shared connection, multiple persons can go to the `/live` view and interact with the desktop all at the same time.
Note: this depends on PR #419.
=> Allow sharing of VNC sessions to enable multiple VNC connections

getgather/mcp/cnn.py, getgather/mcp/main.py, getgather/mcp/patterns/cnn-latest-stories.html
This is using lite.cnn.com. To verify, launch as usual, connect MCP Inspector, and invoke the tool `cnn_get_latest_stories`. In a few seconds, the latest stores in JSON should be retrieved.
=> CNN tool to grab the latest stories without sign in

getgather/mcp/shared.py
Improves error handling in the check `hosted link` by making the response status more accurate and informative.
Currently on the demoapp side, we haven't handle the failed status.
=> fix: handle error link status

.jwmrc, Dockerfile, entrypoint.sh
Useful menu items such as Terminal and Chromium are useful to assist troubleshooting as well.
Before:
After:
=> Style JWM to look slightly more modern

getgather/mcp/dpage.py
This is necessary so that the MCP Gateway can route the tool call to the right instance of MCP server, similar to the way it's done for hosted links.
To verify, run by setting the hostname, e.g.:
```
HOSTNAME=foobar npm run dev
```
and then connect MCP Inspector, invoke a tool that requires distillation, e.g. `bbc_get_saved_articles`. The result is the request to continue with the sign in at a special distilled page, which has `foobar` as the prefix.
=> Take into account the hostname when creating a distilled page

.env.template, getgather/config.py, getgather/main.py
for users who want to add minimal security to their servers they can add a `AUTH_BEARER_TOKEN`
tested with `curl -H 'Authorization: Bearer AUTH_BEARER_TOKEN' localhost:23456/mcp`
=> add simple Bearer token auth
