mcp-getgather/mcp-getgather

getgather/api/main.py, getgather/api/routes/auth/endpoints.py, getgather/api/routes/auth/types.py, getgather/browser/profile.py, getgather/browser/session.py
patchright only works with chromium 
run cnn test to verify
```
❮ CNN_USERNAME=***** CNN_PASSWORD=***** tests/api/test_auth_api.py::test_auth_api_flow
=========================================== test session starts ============================================
platform darwin -- Python 3.11.6, pytest-8.4.1, pluggy-1.6.0 -- /Users/bin/dev/cursor/getgather/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/bin/dev/cursor/getgather
configfile: pytest.ini
plugins: anyio-4.9.0, xdist-3.8.0, cov-6.2.1, asyncio-1.0.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=function, asyncio_default_test_loop_scope=function
collected 1 item                                                                                           
tests/api/test_auth_api.py::test_auth_api_flow[cnn] …
```
=> remove unnecessary browser options

tests/acme_corp/acme_corp.py, tests/acme_corp/email_then_otp_or_pass.py, tests/acme_corp/email_then_password_or_otp.py, tests/connectors/brand_specs/acme-email-then-otp-direct-or-password.yml, tests/connectors/brand_specs/acme-email-then-password-or-otp.yml
Some of the recently added web UI tests are failing because the ACME corp tests involving the user making a choice weren't added yet. I've added the two here that are failing but haven't added them to the auth flow tests yet. This just makes it so that the failing web UI tests will pass.
=> Added failing choice tests to ACME server

.github/workflows/publish.yml
Once it's published, it will be available as `ghcr.io/getgather-hub/getgather`.
=> Automatically test, build, and publish container image

Dockerfile
This is mostly the work from @faisalburhanudin.
To verify, build the image first with e.g. `podman build -t getgather .` and then edit some Python files. Running the build the second time should be still fast.
=> feat: optmize docker layer

.envrc
=> Run uv sync in .envrc

.github/workflows/webui-tests.yml
Speed up slow tests from 9 min to 2 min
=> Run webui tests in parallel

getgather/database/models.py, getgather/database/repositories/activity_repository.py, getgather/database/repositories/brand_state_repository.py, getgather/mcp/main.py
Refactored the database layer to use instance-based methods instead of class methods, improving type safety and API consistency across all repository models.
- **DBModel base class**: Converted from class methods to instance methods (`get`, `add`, `update`)
- **Table naming**: Replaced `_table_name` class variable with `table_name` property
- **Type improvements**: Replaced `TypeVar` with `Self` for better type hints
- **ActivityRepository**: Updated to use instance-based interface with `activity_id` field
- **BrandStateRepository**: Converted `create` method to instance-based pattern
- **Callers updated**: Modified `main.py` to use new repository interfaces
=> Refactor database models to use instance-based methods and table_name property

getgather/connectors/brand_specs/audible/specs.yml, getgather/mcp/brand/audible.py
=> Add Audible spec and mcp

getgather/connectors/brand_specs/amazonca/specs.yml
=> feat: add amazon canada brand spec

getgather/actions.py, getgather/connectors/brand_specs/hardcover/specs.yml, getgather/detect.py, getgather/flow.py, getgather/mcp/brand/hardcover.py
Also make `flow_step` support `autoclick` field
Implement a `get_first_visible` helper function to handle cases where a selector could match single or multiple elements
Verify with Claude Desktop
=> Add Hardcover spec and mcp

getgather/connectors/brand_specs/gofood/specs.yml, getgather/mcp/brand/gofood.py
ad gofood mcp to retrive purchase history
=> feat: add gofood mcp tool

getgather/api/main.py, getgather/mcp/main.py, pyproject.toml
This makes the import structure far cleaner.
=> Cleanup mcp startup

getgather/mcp/brand/amazon.py, getgather/mcp/brand/ebird.py, getgather/mcp/brand/shopee.py, getgather/mcp/brand/tokopedia.py
As per @bin-ario 's suggestions: 
https://github.com/mcp-getgather/mcp-getgather/pull/81#discussion_r2264023268
=> cleanup browser handling

.github/workflows/mcp-tests.yml, .github/workflows/unit-tests.yml, pytest.ini, tests/mcp/test_bbc.py
add tests for bbc mcp (auth & extract)
=> tests: bbc MCP

getgather/mcp/brand/tokopedia.py
Tokopedia MCP tools for search product & add to cart. Support multiple item by opening new tab in the same browser profile.
https://github.com/user-attachments/assets/d414be3b-9ee4-4cb8-8bae-995d3d87bba7
=> feat: tokopedia mcp to search product & add to cart

getgather/actions.py, getgather/connectors/brand_specs/ubereats/specs.yml, getgather/extract_orchestrator.py, getgather/flow.py, getgather/mcp/brand/ubereats.py, getgather/parse.py
Update Ubereats auth spec to handle different options
Add convenient testing code for extract and parse
=> Add ubereats spec and mcp

getgather/api/routes/link/endpoints.py, getgather/logs.py, getgather/mcp/shared.py
Will simplify #125 quite a bit.
=> Improve hosted link logging

entrypoint.sh, getgather/mcp/shared.py
=> Correct tunneling permissions for Ngrok and pinggy

getgather/mcp/brand/ebird.py
Adds an MCP tool to eBird that can submit birds to a checklist.
Some current requirements:
* The location has to exist in your previously visited locations already
* Bird matching is still a little rough (ie if you type the name of the bird without hyphens, it might not pick it up)
Tested on both MCP inspector and Claude desktop and verified it works. Definitely some future improvements to be made like adding new locations, matching birds better (so you don't have to know the hyphens or exact names) and allowing for user input on distance duration.
=> Submit eBird Checklist

frontend/src/components/Layout.tsx, frontend/src/main.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/MCPDocs.tsx, getgather/api/main.py, getgather/mcp/main.py, vite.config.ts
=> Add mcp docs page

frontend/src/pages/MCPDocs.tsx, getgather/mcp/main.py
openapi docs can't handle the full fastcmp Tool model so use a custom one
verify at http://localhost:23456/docs
=> fix openapi docs

getgather/connectors/brand_specs/amazon/specs.yml
As hotly requested by users, we now support number based login.
=> add phone number capability to amazon

frontend/src/components/Layout.tsx, frontend/src/main.tsx, frontend/src/pages/GetStarted.tsx, frontend/src/pages/NotFound.tsx, tests/api/test_webui_auth.py, tests/api/test_webui_list.py
Show GetGather Studio as our main page.
https://github.com/mcp-getgather/mcp-getgather/issues/171
=> feat: replace frontend home page to studio

getgather.py
Note: this is mostly the suggestion/work from @broerjuang. 
To verify, run `./getgather.py list`, which will output something like:
```
INFO     agoda-signin.html
INFO     agoda-booking.html
INFO     agoda-otp.html
INFO     agoda-booking-completed.html
INFO     goodreads-select-signin.html
INFO     goodreads-books.html
INFO     goodreads-signin.html
INFO     goodreads-siteheader.html
INFO     goodreads-overlay.html
INFO     goodreads-signup.html
```
=> Use glob to search for all distillation patterns

getgather/mcp/brand/officedepot.py, getgather/mcp/brand/wayfair.py
=> add mcp tools for wayfair & officedepot

getgather.py
To verify, run `./getgather.py run https://goodreads.com/review`. Email and password to sign in to Goodreads will be prompted, and at the end, the distilled HTML representing the bookshelf will be printed out.
=> For the distillation CLI, use the existing browser implementation

frontend/src/components/Layout.tsx, frontend/src/lib/config.ts, frontend/src/main.tsx, frontend/src/pages/MCPDocs.tsx, frontend/src/pages/config.ts, getgather/api/api.py, getgather/main.py, getgather/mcp/stagehand_agent.py
disable activities, inspector, and replay in multi-user mode
=> disable more features in multi-user mode

getgather/mcp/patterns/linkedin-feed.html, getgather/mcp/patterns/linkedin-signin.html
=> feat: linkedin distill pattern

getgather/connectors/brand_specs/aliexpress/specs.yml, getgather/mcp/brand/aliexpress.py, getgather/mcp/patterns/aliexpress-orders.html
Add aliexpress mcp tool to extract order
=> feat: aliexpress mcp tool

getgather/mcp/brand/petsmart.py, getgather/mcp/patterns/petsmart-cart.html
=> refactor: petsmart to distillation

getgather/connectors/brand_specs/shein/specs.yml, getgather/mcp/brand/shein.py, getgather/mcp/patterns/shein-orders.html
=> refactor: shine to distillation (extraction)

getgather/connectors/brand_specs/horizonhobby/specs.yml, getgather/mcp/brand/horizonhobby.py, getgather/mcp/patterns/horizon-hobby-order.html
=> refactor: horizon hobby to distillation

getgather/connectors/brand_specs/doordash/specs.yml, getgather/mcp/brand/doordash.py, getgather/mcp/patterns/doordash-orders.html
eed to check actual doordash account. This changes made following the spec from doordash/spec.yml
=> refactor: doordash orders using distillation 

getgather/connectors/brand_specs/audible/specs.yml, getgather/mcp/brand/audible.py, getgather/mcp/patterns/audible-library.html
Not tested the parser yet. Need help from someone who has an account and have data to test this.
I'm also adding OTP spec for audible.
=> refactor: audible extract using distillation

getgather/connectors/brand_specs/ebay/specs.yml, getgather/mcp/brand/ebay.py, getgather/mcp/patterns/ebay-order-history.html
=> refactor: ebay to distillation

entrypoint.sh, getgather/browser/profile.py
This adds auth for the xserver and actually checks to see if the server is really running or not as opposed to the socket being present. 
https://www.mankier.com/1/
https://man.archlinux.org/man/X.7.en
=> Add xauth for xvfb

getgather/connectors/brand_specs/ubereats/specs.yml, getgather/mcp/brand/ubereats.py, getgather/mcp/patterns/ubereats-orders.html
Not tested yet. Need help from someone who has an account to test this.
=> refactor: extract ubereats using distillation

getgather/mcp/dpage.py
This is a follow-up to PR #385. Apparently the default scheme can't be always `https`, particularly when the Host is local.
To verify, `npm run dev`, connect MCP inspector, and invoke the tool `bbc_get_saved_article`. The link returned should should the base URL `http://localhost:23456`.
Before this PR, the base URL will use `https`, which leads to a failure.
=> Have a proper default scheme when creating a distilled page

tests/distillation/test_distill.py
Realized that there was another simple distillation test we could add based on what was already there.
Thanks for everything team!
=> Final PR! - Adding simple distillation test

getgather/browser/profile.py, getgather/config.py, getgather/parse.py
The global `BROWSER_TIMEOUT` can be changed via env variable
=> set a global browser timeout

getgather/actions.py, getgather/flow.py
BROWSER_TIMEOUT can be configured via env variable
=> use BROWSER_TIMEOUT to replace hardcoded one

getgather/connectors/brand_specs/lululemon/specs.yml, getgather/mcp/brand/lululemon.py, getgather/mcp/patterns/lululemon-orders.html
actual site doesn't have info about the product name. Maybe need to dive in detail purchase
=> refactor: lululemon distill (extract, parse, mcp-tool)

getgather/connectors/brand_specs/chewy/specs.yml, getgather/mcp/brand/chewy.py, getgather/mcp/patterns/chewy-orders.html
=> refactor: chewy distillation (extraction, mcp-tool)

getgather/mcp/brand/goodreads.py
Fixed the Goodreads book list retrieval by adding query parameters to ensure the page loads in table view format, which is necessary for proper data extraction.
https://github.com/user-attachments/assets/0bc8c8d6-71e7-4879-b39a-4abe90e2ded3
=> fix: add table view parameter to goodreads book list url
